import { useEffect, useState } from "react";
import { PlatformLayout } from "@/components/PlatformLayout";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";

type Riddle = {
  id: string;
  question: string;
  answer: string;
};

export default function Riddles() {
  const [riddles, setRiddles] = useState<Riddle[]>([]);
  const [answers, setAnswers] = useState<Record<string, string>>({});
  const [results, setResults] = useState<Record<string, string>>({});
  const [showAnswers, setShowAnswers] = useState<Record<string, boolean>>({});
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fetchRiddles = async () => {
      try {
        setLoading(true);
        setError(null);
        const res = await fetch("/api/riddles");
        if (!res.ok) {
          throw new Error("Failed to load riddles");
        }
        const data = (await res.json()) as { riddles: Riddle[] };
        setRiddles(data.riddles ?? []);
      } catch (err) {
        setError((err as Error).message ?? "Something went wrong");
      } finally {
        setLoading(false);
      }
    };

    fetchRiddles();
  }, []);

  const handleChange = (id: string, value: string) => {
    setAnswers((prev) => ({ ...prev, [id]: value }));
  };

  const handleCheck = (riddle: Riddle) => {
    const userAnswer = (answers[riddle.id] ?? "").trim().toLowerCase();
    const correctAnswer = riddle.answer.trim().toLowerCase();

    if (!userAnswer) {
      setResults((prev) => ({
        ...prev,
        [riddle.id]: "Type your answer first.",
      }));
      return;
    }

    const isCorrect = userAnswer === correctAnswer;
    setResults((prev) => ({
      ...prev,
      [riddle.id]: isCorrect
        ? "✅ Correct!"
        : "❌ Not quite. Try again or reveal the answer.",
    }));
  };

  const handleShowAnswer = (riddle: Riddle) => {
    setShowAnswers((prev) => ({ ...prev, [riddle.id]: true }));
    setResults((prev) => ({
      ...prev,
      [riddle.id]: `The correct answer is: ${riddle.answer}`,
    }));
  };

  return (
    <PlatformLayout
      title="Riddles"
      description="Challenge your mind with mind-bending riddles. These 5 riddles are generated by AI each time you visit."
    >
      <div className="mt-10 space-y-6">
        {loading && <p className="text-slate-300">Loading riddles...</p>}
        {error && <p className="text-red-400">{error}</p>}

        {!loading && !error && riddles.length === 0 && (
          <p className="text-slate-400">No riddles available right now.</p>
        )}

        <div className="grid gap-6">
          {riddles.map((riddle, index) => (
            <Card
              key={riddle.id}
              className="bg-gradient-to-br from-slate-900 to-slate-950 border-slate-800"
            >
              <CardHeader>
                <CardTitle className="text-lg text-white">
                  Riddle {index + 1}
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <p className="text-slate-200">{riddle.question}</p>
                <div className="flex flex-col gap-3 sm:flex-row sm:items-center">
                  <Input
                    placeholder="Type your answer..."
                    value={answers[riddle.id] ?? ""}
                    onChange={(e) => handleChange(riddle.id, e.target.value)}
                    className="sm:max-w-md"
                    disabled={showAnswers[riddle.id]}
                  />
                  <div className="flex gap-2">
                    <Button
                      onClick={() => handleCheck(riddle)}
                      className="bg-gradient-to-r from-primary to-secondary"
                      disabled={showAnswers[riddle.id]}
                    >
                      Check answer
                    </Button>
                    {!showAnswers[riddle.id] && (
                      <Button
                        onClick={() => handleShowAnswer(riddle)}
                        variant="outline"
                        className="border-primary/60 text-slate-200 hover:bg-primary/10"
                      >
                        Show answer
                      </Button>
                    )}
                  </div>
                </div>
                {results[riddle.id] && (
                  <p className="text-sm text-slate-300">{results[riddle.id]}</p>
                )}
              </CardContent>
            </Card>
          ))}
        </div>
      </div>
    </PlatformLayout>
  );
}
